spring:
  application:
    name: spring-cloud-gateway-kotlin

  cloud:
    gateway:
      routes:
        - id: hello-world
          uri: https://httpbin.org
          predicates:
            - Path=/get
